# Generated by Django 4.2.1 on 2023-07-16 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 11, 41, 56, 908950)),
        ),
    ]
